-- V1__crear_tabla_carrito_items.sql
CREATE TABLE IF NOT EXISTS carrito_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT      NOT NULL,
    producto_id BIGINT     NOT NULL,
    cantidad   INT         NOT NULL
);
