-- V1__crear_tabla_despachos.sql
CREATE TABLE IF NOT EXISTS despachos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id        BIGINT       NOT NULL,
    direccion        VARCHAR(255) NOT NULL,
    comuna           VARCHAR(100) NOT NULL,
    estado           VARCHAR(50)  NOT NULL,
    fecha_programada DATE
);
