-- V1__crear_tabla_pagos.sql
CREATE TABLE IF NOT EXISTS pagos (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id  BIGINT       NOT NULL,
    metodo     VARCHAR(100) NOT NULL,
    monto      INT          NOT NULL,
    estado     VARCHAR(50)  NOT NULL,
    fecha_pago TIMESTAMP
);
