server:
  port: ${PORT:8084}

spring:
  application:
    name: carrito-service
  profiles:
    active: local

  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    duoc: INFO
    org.springframework.web: WARN

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

---
# ── PERFIL LOCAL ─────────────────────────────────────
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/db_carrito?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

---
# ── PERFIL PRODUCCIÓN ─────────────────────────────────
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://dpg-d97b08urnols73ckjr60-a:5432/tecnosmart
    driver-class-name: org.postgresql.Driver
    username: tecnosmart_user
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration